# Data Science & AI

**M2: Python Untuk Data Science**

Nama&emsp;&emsp;:Iman Rahman <br>
Kelompok:

**Daftar Halaman**:
1. Pengantar Markdown
2. Pengantar Python
3. Pandas Package

## Pengantar Markdown

### Text style

**Bold text**<br>
*Italic text*<br>
***Bold and italic***<br>
~~Strikethrough~~<br>
<u>underline</u><br>

### Image

![Logo Vinix7](\modul_2\Logo.png)

### Equation

The energy-momentum relation is given by $E^2=(pc)^2+(m_0c^2)^2$.

$$\oint_S\mathbf{E}\cdot d\mathbf{A}=\frac{Q}{\varepsilon_0}$$

## Pengantar Python

In [ ]:
import sys
print(sys.executable)

c:\Users\abdul\miniconda3\envs\vinix7\python.exe

In [2]:
!python --version
!pip list

Python 3.10.19
Package                   Version
------------------------- -----------
anyio                     4.10.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.4.0
babel                     2.17.0
beautifulsoup4            4.14.3
bleach                    6.3.0
Bottleneck                1.4.2
brotlicffi                1.2.0.0
certifi                   2026.1.4
cffi                      2.0.0
charset-normalizer        3.4.4
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.16
decorator                 5.2.1
defusedxml                0.7.1
et_xmlfile                2.0.0
exceptiongroup            1.3.0
executing                 2.2.1
fastjsonschema            2.21.2
h11                       0.16.0
html5lib                  1.1
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 6.31.0
ipython                   8.30.0
ipython_pygments_lexers   1.1.1
ipywidgets                8.1.7
jedi                      0.19.2
Jinja2                    3.1.6
json5                     0.12.1
jsonschema                4.25.1
jsonschema-specifications 2025.9.1
jupyter                   1.1.1
jupyter_client            8.8.0
jupyter-console           6.6.3
jupyter_core              5.9.1
jupyter-events            0.12.0
jupyter-lsp               2.3.0
jupyter_server            2.17.0
jupyter_server_terminals  0.5.4
jupyterlab                4.5.3
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
jupyterlab_widgets        3.0.16
MarkupSafe                3.0.2
matplotlib-inline         0.2.1
mistune                   3.1.2
mkl_fft                   2.1.1
mkl_random                1.3.0
mkl-service               2.5.2
nbclient                  0.10.4
nbconvert                 7.17.0
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.5.3
notebook_shim             0.2.4
numexpr                   2.14.1
numpy                     2.2.5
openpyxl                  3.1.5
overrides                 7.7.0
packaging                 25.0
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.5
pip                       26.0.1
platformdirs              4.5.0
prometheus_client         0.21.1
prompt_toolkit            3.0.52
psutil                    7.0.0
pure_eval                 0.2.3
pycparser                 2.23
Pygments                  2.19.2
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-json-logger        4.0.0
pytz                      2025.2
pywin32                   311
pywinpty                  2.0.15
PyYAML                    6.0.3
pyzmq                     27.1.0
qtconsole                 5.7.1
QtPy                      2.4.3
referencing               0.37.0
requests                  2.32.5
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.28.0
Send2Trash                1.8.3
setuptools                80.10.2
six                       1.17.0
sniffio                   1.3.1
soupsieve                 2.5
stack_data                0.6.3
terminado                 0.18.1
tinycss2                  1.4.0
tomli                     2.4.0
tornado                   6.5.4
traitlets                 5.14.3
typing_extensions         4.15.0
tzdata                    2025.3
urllib3                   2.6.3
wcwidth                   0.2.14
webencodings              0.5.1
websocket-client          1.8.0
wheel                     0.46.3
widgetsnbextension        4.0.14
win_inet_pton             1.1.0

In [3]:
# Mendefinisikan variabel
nama_produk = "Nampan Kayu"    # String (Teks)
harga = 45000                  # Integer (Bilangan Bulat)
berat_kg = 1.25                # Float (Bilangan Desimal)
apakah_tersedia = True         # Boolean (Benar/Salah)

# Menampilkan nilai dan tipe datanya
print(f"Produk: {nama_produk} | Tipe: {type(nama_produk)}")
print(f"Harga : {harga} | Tipe: {type(harga)}")
print(f"Berat : {berat_kg} | Tipe: {type(berat_kg)}")
print(f"Tersedia : {apakah_tersedia} | Tipe: {type(apakah_tersedia)}")

Produk: Nampan Kayu | Tipe: <class 'str'>
Harga : 45000 | Tipe: <class 'int'>
Berat : 1.25 | Tipe: <class 'float'>
Tersedia : True | Tipe: <class 'bool'>

In [4]:
# List: Kumpulan data berurutan
daftar_bulan = ["Januari", "Februari", "Maret"]
print(f"Bulan pertama dalam list: {daftar_bulan[0]}")

# Dictionary: Data berpasangan (Label: Nilai)
detail_toko = {
    "nama": "Toko Vinix",
    "lokasi": "Yogyakarta",
    "rating": 4.8
}
print(f"Lokasi Toko: {detail_toko['lokasi']}")

Bulan pertama dalam list: Januari
Lokasi Toko: Yogyakarta

In [5]:
import pandas as pd
import numpy as np

# Mengecek apakah library sudah siap
print(f"Pandas version: {pd.__version__}")
print("Library berhasil dipanggil dan siap digunakan!")

Pandas version: 2.3.3
Library berhasil dipanggil dan siap digunakan!

In [6]:
# Membuat DataFrame sederhana dari Dictionary
data_mentah = {
    'Produk': ['Celengan', 'Nampan', 'Peralatan Makan'],
    'Berat': ['500 gr', '1200 gr', '150 gr'],
    'Status': ['Selesai', 'Selesai', 'Batal']
}

df = pd.DataFrame(data_mentah)

# Menampilkan tabel
df

            Produk    Berat   Status
0         Celengan   500 gr  Selesai
1           Nampan  1200 gr  Selesai
2  Peralatan Makan   150 gr    Batal

## Pandas Package

In [7]:
# Membaca dataset demo
df_demo = pd.read_csv('demo_dataset_m2.csv')

# Melihat 5 baris pertama
print("Tampilan Awal Data:")
display(df_demo.head())

# Mengecek daftar kolom dan tipe data
print("\nInformasi Struktur Data:")
df_demo.info()

Tampilan Awal Data:

,tanggal,stasiun,pm25,pm10,so2,co,o3,no2,max,critical,categori
0,2010-01-01,DKI1 (Bunderan HI),NaN,60.0,4.0,73.0,27.0,14.0,73.0,CO,SEDANG
1,2010-01-02,DKI1 (Bunderan HI),NaN,32.0,2.0,16.0,33.0,9.0,33.0,O3,BAIK
2,2010-01-03,DKI1 (Bunderan HI),NaN,27.0,2.0,19.0,20.0,9.0,27.0,PM10,BAIK
3,2010-01-04,DKI1 (Bunderan HI),NaN,22.0,2.0,16.0,15.0,6.0,22.0,PM10,BAIK
4,2010-01-05,DKI1 (Bunderan HI),NaN,25.0,2.0,17.0,15.0,8.0,25.0,PM10,BAIK

Informasi Struktur Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5538 entries, 0 to 5537
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   5538 non-null   object
 1   stasiun   5537 non-null   object
 2   pm25      1516 non-null   float64
 3   pm10      5223 non-null   float64
 4   so2       5408 non-null   float64
 5   co        5450 non-null   float64
 6   o3        5434 non-null   float64
 7   no2       5432 non-null   float64
 8   max       5537 non-null   float64
 9   critical  5534 non-null   object
 10  categori  5538 non-null   object
dtypes: float64(7), object(4)
memory usage: 476.0+ KB

In [8]:
# 1. Konversi Kolom Tanggal menjadi tipe Datetime
df_demo['tanggal'] = pd.to_datetime(df_demo['tanggal'])

# 2. Menangani Missing Values (NaN)
# Mengisi nilai kosong pada polutan dengan angka 0 (atau bisa menggunakan rata-rata/mean)
df_demo['pm10'] = df_demo['pm10'].fillna(0)

# 3. Menghapus kolom yang terlalu banyak kosong (seperti pm25 jika tidak diperlukan)
df_clean = df_demo.drop(columns=['pm25'])

print("Data setelah pembersihan awal:")
df_clean.head()

Data setelah pembersihan awal:

,tanggal,stasiun,pm10,so2,co,o3,no2,max,critical,categori
0,2010-01-01,DKI1 (Bunderan HI),60.0,4.0,73.0,27.0,14.0,73.0,CO,SEDANG
1,2010-01-02,DKI1 (Bunderan HI),32.0,2.0,16.0,33.0,9.0,33.0,O3,BAIK
2,2010-01-03,DKI1 (Bunderan HI),27.0,2.0,19.0,20.0,9.0,27.0,PM10,BAIK
3,2010-01-04,DKI1 (Bunderan HI),22.0,2.0,16.0,15.0,6.0,22.0,PM10,BAIK
4,2010-01-05,DKI1 (Bunderan HI),25.0,2.0,17.0,15.0,8.0,25.0,PM10,BAIK

In [9]:
# Mencari data di mana kategori udara 'TIDAK SEHAT'
kondisi_buruk = df_clean[df_clean['categori'] == 'TIDAK SEHAT']

print(f"Ditemukan {len(kondisi_buruk)} hari dengan kualitas udara TIDAK SEHAT.")
kondisi_buruk[['tanggal', 'stasiun', 'max', 'critical']].head()

Ditemukan 1827 hari dengan kualitas udara TIDAK SEHAT.

       tanggal             stasiun    max critical
97  2010-04-08  DKI1 (Bunderan HI)  102.0       O3
145 2010-05-26  DKI1 (Bunderan HI)  123.0       O3
146 2010-05-27  DKI1 (Bunderan HI)  113.0       O3
283 2010-10-11  DKI1 (Bunderan HI)  111.0       O3
314 2010-11-11    DKI3 (Jagakarsa)  126.0       O3

In [10]:
# Menghitung rata-rata nilai polutan maksimal per stasiun
analisis_stasiun = df_clean.groupby('stasiun')['max'].mean().sort_values(ascending=False)

print("Rata-rata Nilai Maksimal Polutan per Stasiun:")
print(analisis_stasiun)

Rata-rata Nilai Maksimal Polutan per Stasiun:
stasiun
DKI2 (Kelapa Gading)    117.421284
DKI5 (Kebon Jeruk)      107.752549
DKI4 (Lubang Buaya)      93.475508
DKI3 (Jagakarsa)         90.131720
DKI1 (Bunderan HI)       63.426415
Name: max, dtype: float64


**Laporan Singkat:** <br>
Ini adalah laporan singkat