# Modul 2: Python untuk Data Science (Kelompok 17)

Nama anggota :<br>
Abdulhadi Muntashir <br>
M Hafid Ramadhan <br>
Naufal Pancar Nugraha

In [4]:
import sys
print(sys.executable)

c:\Users\abdul\miniconda3\envs\vinix7\python.exe

In [5]:
#tahap 1: Import Library & standarisasi data
import pandas as pd
import os

folder_path = r"G:\Project\VINIX7\modul_2\Dataset_M2"

unique_columns = set()

for file in os.listdir(folder_path):
    if file.endswith(".xlsx"):
        file_path = os.path.join(folder_path, file)
        df = pd.read_excel(file_path, nrows=0)

        for col in df.columns:
            unique_columns.add(col)

print("Daftar semua kolom unik:\n")

for col in sorted(unique_columns):
    print(col)

Daftar semua kolom unik:

Alamat Pengiriman
Alasan Pembatalan
Antar ke counter/ pick-up
Berat Produk
Cashback Koin
Catatan
Catatan dari Pembeli
Diskon Dari Penjual
Diskon Dari Shopee
Diskon Kartu Kredit
Estimasi Potongan Biaya Pengiriman
Harga Awal
Harga Setelah Diskon
Jumlah
Jumlah Produk di Pesan
Kota/Kabupaten
Metode Pembayaran
Nama Penerima
Nama Variasi
No. Resi
No. Telepon
Nomor Referensi SKU
Ongkos Kirim Dibayar oleh Pembeli
Ongkos Kirim Pengembalian Barang
Opsi Pengiriman
Paket Diskon
Paket Diskon (Diskon dari Penjual)
Paket Diskon (Diskon dari Shopee)
Perkiraan Ongkos Kirim
Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan)
Potongan Koin Shopee
Provinsi
Returned quantity
SKU Induk
Status Pembatalan/ Pengembalian
Status Pesanan
Total Berat
Total Diskon
Total Harga Produk
Total Pembayaran
Username (Pembeli)
Voucher Ditanggung Penjual
Voucher Ditanggung Shopee
Waktu Pembayaran Dilakukan
Waktu Pengiriman Diatur
Waktu Pesanan Dibuat
Waktu Pesanan Selesai
order_id
product_category

In [6]:
column_frequency = {}

for file in os.listdir(folder_path):

    if file.endswith(".xlsx"):
        file_path = os.path.join(folder_path, file)
        df = pd.read_excel(file_path, nrows=0)

        for col in df.columns:
            if col in column_frequency:
                column_frequency[col] += 1
            else:
                column_frequency[col] = 1

print("\nFrekuensi kemunculan kolom:\n")

for col, count in sorted(column_frequency.items(), key=lambda x: x[1], reverse=True):
    print(f"{col} : {count}")

Frekuensi kemunculan kolom:

order_id : 24
product_category : 24
Status Pesanan : 24
Alasan Pembatalan : 24
Opsi Pengiriman : 24
Metode Pembayaran : 24
Jumlah : 24
Returned quantity : 24
Total Diskon : 24
Total Berat : 24
Ongkos Kirim Dibayar oleh Pembeli : 24
Estimasi Potongan Biaya Pengiriman : 24
Total Pembayaran : 24
Perkiraan Ongkos Kirim : 24
Kota/Kabupaten : 24
Provinsi : 24
Waktu Pesanan Dibuat : 22
Waktu Pengiriman Diatur : 3
Status Pembatalan/ Pengembalian : 1
No. Resi : 1
Antar ke counter/ pick-up : 1
Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan) : 1
Waktu Pembayaran Dilakukan : 1
SKU Induk : 1
Nomor Referensi SKU : 1
Nama Variasi : 1
Harga Awal : 1
Harga Setelah Diskon : 1
Total Harga Produk : 1
Diskon Dari Penjual : 1
Diskon Dari Shopee : 1
Berat Produk : 1
Jumlah Produk di Pesan : 1
Voucher Ditanggung Penjual : 1
Cashback Koin : 1
Voucher Ditanggung Shopee : 1
Paket Diskon : 1
Paket Diskon (Diskon dari Shopee) : 1
Paket Diskon (Diskon dari Penjual) : 1
Potongan Koin Shopee : 1
Diskon Kartu Kredit : 1
Ongkos Kirim Pengembalian Barang : 1
Catatan dari Pembeli : 1
Catatan : 1
Username (Pembeli) : 1
Nama Penerima : 1
No. Telepon : 1
Alamat Pengiriman : 1
Waktu Pesanan Selesai : 1

In [7]:
standard_columns = [
    "order_id",
    "product_category",
    "Status Pesanan",
    "Alasan Pembatalan",
    "Opsi Pengiriman",
    "Metode Pembayaran",
    "Jumlah",
    "Returned quantity",
    "Total Diskon",
    "Total Berat",
    "Ongkos Kirim Dibayar oleh Pembeli",
    "Estimasi Potongan Biaya Pengiriman",
    "Total Pembayaran",
    "Perkiraan Ongkos Kirim",
    "Kota/Kabupaten",
    "Provinsi",
    "order_created_time"
]

In [8]:
filtered_data = []

for file in os.listdir(folder_path):

    if file.endswith(".xlsx"):

        file_path = os.path.join(folder_path, file)

        df = pd.read_excel(file_path)

        # standardisasi nama kolom waktu
        df = df.rename(columns={
            "Waktu Pesanan Dibuat": "order_created_time",
            "Waktu Pembayaran Dilakukan": "payment_time",
            "Waktu Pesanan Selesai": "order_finished_time"
        })

        cols = [c for c in standard_columns if c in df.columns]

        df_filtered = df[cols]

        filtered_data.append(df_filtered)

In [9]:
df_master = pd.concat(filtered_data, ignore_index=True)

print(df_master.info())
print(df_master.shape)

df_master.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26258 entries, 0 to 26257
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   order_id                            26258 non-null  object
 1   product_category                    26258 non-null  object
 2   Status Pesanan                      26258 non-null  object
 3   Alasan Pembatalan                   3525 non-null   object
 4   Opsi Pengiriman                     26258 non-null  object
 5   Metode Pembayaran                   26258 non-null  object
 6   Jumlah                              26258 non-null  int64
 7   Returned quantity                   24923 non-null  float64
 8   Total Diskon                        26258 non-null  float64
 9   Total Berat                         26258 non-null  object
 10  Ongkos Kirim Dibayar oleh Pembeli   26258 non-null  float64
 11  Estimasi Potongan Biaya Pengiriman  26258 non-null  float64
 12  Total Pembayaran                    26258 non-null  object
 13  Perkiraan Ongkos Kirim              26258 non-null  float64
 14  Kota/Kabupaten                      26258 non-null  object
 15  Provinsi                            26258 non-null  object
 16  order_created_time                  23824 non-null  object
dtypes: float64(5), int64(1), object(11)
memory usage: 3.4+ MB
None
(26258, 17)

,order_id,product_category,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Jumlah,Returned quantity,Total Diskon,Total Berat,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Kota/Kabupaten,Provinsi,order_created_time
0,ORD_0000001,Celengan,Selesai,NaN,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,1,0.0,0.0,1000 gr,0.0,10.0,38.300,10.0,KOTA SERANG,BANTEN,2024-04-01 00:15
1,ORD_0000001,Celengan,Selesai,NaN,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,1,0.0,0.0,1000 gr,0.0,10.0,38.300,10.0,KOTA SERANG,BANTEN,2024-04-01 00:15
2,ORD_0000002,Celengan,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),1,0.0,0.0,500 gr,0.0,14.5,18.576,14.5,KOTA SEMARANG,JAWA TENGAH,2024-04-01 01:47
3,ORD_0000003,Celengan,Selesai,NaN,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,1,0.0,0.0,500 gr,0.0,8.0,7.069,8.0,KAB. BOGOR,JAWA BARAT,2024-04-01 04:25
4,ORD_0000004,Mangkok Sambal / Saus,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),2,0.0,0.0,400 gr,0.0,20.0,32.200,20.0,KOTA JAMBI,JAMBI,2024-04-01 04:41

In [10]:
# Tahap 2: Data Cleaning
df_master["Alasan Pembatalan"] = df_master["Alasan Pembatalan"].fillna("Tidak Batal")
print(df_master["Alasan Pembatalan"].value_counts())

Alasan Pembatalan
Tidak Batal                                                                                                                                           22733
Dibatalkan oleh Pembeli. Alasan: Lainnya/ berubah pikiran                                                                                               729
Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan yang Ada                                                                                                  704
Dibatalkan secara otomatis oleh sistem. Alasan: Pesanan belum dibayar                                                                                   585
Dibatalkan oleh Pembeli. Alasan: Need to change delivery address                                                                                        400
Dibatalkan secara otomatis oleh sistem. Alasan: Pengiriman gagal                                                                                        297
Dibatalkan oleh Pembeli. Alasan: Perlu mengubah alamat pengiriman                                                                                       144
Dibatalkan oleh Pembeli. Alasan: Perlu mengubah pesanan                                                                                                 142
Dibatalkan secara otomatis oleh sistem. Alasan: Penjual gagal mengirimkan pesanan tepat waktu                                                           142
Dibatalkan secara otomatis oleh sistem. Alasan: Penjual tidak mengatur pengiriman tepat waktu                                                            88
Dibatalkan oleh Pembeli. Alasan: Lainnya                                                                                                                 58
Dibatalkan oleh Pembeli. Alasan: Perlu mengubah Voucher                                                                                                  53
Dibatalkan oleh Pembeli. Alasan: Penjual tidak responsif terhadap pertanyaan Pembeli                                                                     44
Dibatalkan oleh Pembeli. Alasan: Proses pembayaran sulit                                                                                                 42
Dibatalkan secara otomatis oleh sistem. Alasan: Paket hilang di perjalanan. Kompensasi yang memenuhi syarat telah dikreditkan ke Saldo Penjual-mu.       29
Dibatalkan oleh Pembeli. Alasan: Tidak ingin membeli lagi                                                                                                24
Dibatalkan oleh Pembeli. Alasan: Menemukan yang lebih murah                                                                                              23
Dibatalkan oleh Penjual. Alasan: Produk habis                                                                                                            15
Dibatalkan secara otomatis oleh sistem. Alasan: Lainnya                                                                                                   6
Name: count, dtype: int64

In [11]:
# Versi lebih robust untuk menghapus "gr"
df_master["Total Berat"] = (
    df_master["Total Berat"]
    .astype(str)
    .str.replace("gr", "", case=False, regex=False)
    .str.strip()
)
df_master["Total Berat"] = pd.to_numeric(
    df_master["Total Berat"], errors="coerce")

In [12]:
df_master["order_created_time"] = pd.to_datetime(df_master["order_created_time"], errors="coerce")

print(df_master["order_created_time"].dtype)

datetime64[ns]

In [13]:
print("Jumlah baris sebelum hapus duplikat:", df_master.shape[0])

df_master = df_master.drop_duplicates()

print("Jumlah baris setelah hapus duplikat:", df_master.shape[0])

print(df_master.info())

Jumlah baris sebelum hapus duplikat: 26258
Jumlah baris setelah hapus duplikat: 23639
<class 'pandas.core.frame.DataFrame'>
Index: 23639 entries, 0 to 26257
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   order_id                            23639 non-null  object
 1   product_category                    23639 non-null  object
 2   Status Pesanan                      23639 non-null  object
 3   Alasan Pembatalan                   23639 non-null  object
 4   Opsi Pengiriman                     23639 non-null  object
 5   Metode Pembayaran                   23639 non-null  object
 6   Jumlah                              23639 non-null  int64
 7   Returned quantity                   22470 non-null  float64
 8   Total Diskon                        23639 non-null  float64
 9   Total Berat                         23639 non-null  int64
 10  Ongkos Kirim Dibayar oleh Pembeli   23639 non-null  float64
 11  Estimasi Potongan Biaya Pengiriman  23639 non-null  float64
 12  Total Pembayaran                    23639 non-null  object
 13  Perkiraan Ongkos Kirim              23639 non-null  float64
 14  Kota/Kabupaten                      23639 non-null  object
 15  Provinsi                            23639 non-null  object
 16  order_created_time                  21426 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(2), object(9)
memory usage: 3.2+ MB
None

In [14]:
# Tahap 3: Data Wrangling & Manipulasi

df_sukses = df_master[df_master["Status Pesanan"].isin(["Selesai", "Telah Dikirim"])]

print(df_sukses.shape)
df_sukses.head()

(20180, 17)

,order_id,product_category,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Jumlah,Returned quantity,Total Diskon,Total Berat,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Kota/Kabupaten,Provinsi,order_created_time
0,ORD_0000001,Celengan,Selesai,Tidak Batal,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,1,0.0,0.0,1000,0.0,10.0,38.300,10.0,KOTA SERANG,BANTEN,2024-04-01 00:15:00
2,ORD_0000002,Celengan,Selesai,Tidak Batal,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),1,0.0,0.0,500,0.0,14.5,18.576,14.5,KOTA SEMARANG,JAWA TENGAH,2024-04-01 01:47:00
3,ORD_0000003,Celengan,Selesai,Tidak Batal,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,1,0.0,0.0,500,0.0,8.0,7.069,8.0,KAB. BOGOR,JAWA BARAT,2024-04-01 04:25:00
4,ORD_0000004,Mangkok Sambal / Saus,Selesai,Tidak Batal,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),2,0.0,0.0,400,0.0,20.0,32.200,20.0,KOTA JAMBI,JAMBI,2024-04-01 04:41:00
8,ORD_0000006,Celengan,Selesai,Tidak Batal,Hemat Kargo-SPX Hemat,SPayLater,2,0.0,0.0,1000,0.0,10.0,40.996,10.0,KAB. BANDUNG,JAWA BARAT,2024-04-01 07:09:00

In [15]:
top_product_category = (
    df_sukses
    .groupby("product_category")["Jumlah"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_product_category)

product_category
Nampan / Tray             8455
Mangkok Sambal / Saus     7014
Celengan                  6515
Aksesoris Pintu           4012
Lunch Box / Rantang       2386
Seal / Baut / Roof        1899
Baskom / Mangkok Besar    1322
Keranjang                 1155
Other                     1037
Botol / Gelas / Mug        991
Name: Jumlah, dtype: int64

In [16]:
top_product_category = (
    df_sukses
    .groupby("product_category", as_index=False)["Jumlah"]
    .sum()
    .sort_values(by="Jumlah", ascending=False)
    .head(10)
)

print(top_product_category)

          product_category  Jumlah
15           Nampan / Tray    8455
14   Mangkok Sambal / Saus    7014
7                 Celengan    6515
3          Aksesoris Pintu    4012
12     Lunch Box / Rantang    2386
29      Seal / Baut / Roof    1899
5   Baskom / Mangkok Besar    1322
11               Keranjang    1155
16                   Other    1037
6      Botol / Gelas / Mug     991

### Mini Report Hasil Data Wrangling

Hasil analisis menunjukkan bahwa tiga kategori produk dengan jumlah penjualan tertinggi adalah **Nampan / tray**, **Mangkok Sambal / Saus**, dan **Celengan** berdasarkan akumulasi nilai pada kolom *Jumlah*. Hal ini menunjukkan bahwa ketiga kategori tersebut memiliki tingkat permintaan yang paling tinggi dibandingkan kategori lainnya pada dataset penjualan yang dianalisis. Informasi ini sangat penting bagi perusahaan untuk menentukan prioritas pengadaan stok, strategi promosi, serta optimalisasi distribusi produk agar lebih efisien. Dengan memfokuskan sumber daya pada kategori dengan performa penjualan tertinggi, perusahaan dapat meningkatkan efisiensi operasional sekaligus memaksimalkan potensi pendapatan.